export const teacherListActions = {
  CREATE_TEACHER: "CREATE_TEACHER",
  READ_TEACHERS: "READ_TEACHERS",
  UPDATE_TEACHER: "UPDATE_TEACHER",
  DELETE_TEACHER: "DELETE_TEACHER",
  DELETE_ALL: "DELETE_ALL"
}